### ISSUE TITLE
Maintainers wanted!

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s-twirl#1]
Please comment if you are interested in helping to maintain this module :) Thanks!

**Comment by fserra-mdsol** [comment]
Hi @armanbilge I would be interested - how can I help? :-)

**Comment by FrancescoSerra** [comment]
Hi @armanbilge I would be interested - how can I help? :-)

**Comment by armanbilge** [comment]
@FrancescoSerra thank you for volunteering! Pinging @rossabaker to help get you setup.

The most pressing matter is to release a new milestone of http4s-twirl built against http4s core 1.0.0-M33. At least one person on the Typelevel Discord was looking for it. I've opened https://github.com/http4s/http4s-twirl/pull/6 to bootstrap that process.

**Comment by rossabaker** [comment]
Thanks, @FrancescoSerra!  I invited you to a new team with Write access to this repo.  You should be able to approve changes, merge, and draft releases.  You can practice by reviewing and merging #6. :smile:  You should also have access to the [maintainers discussions](https://github.com/orgs/http4s/teams/maintainers) to reach a wider audience.

**Comment by FrancescoSerra** [comment]
Thanks, @rossabaker ! Looks like I don't have access to the maintainers discussions, as Github is returning to me a sad 404...

**Comment by kailuowang** [comment]
My work depends on this module. I'd love to help maintain as well.

**Comment by armanbilge** [comment]
Wonderful, thank you! @rossabaker can add you to the team and I think with 2x maintainers we can close this issue out :)

**Comment by FrancescoSerra** [comment]
<3

**Comment by rossabaker** [comment]
Invite sent.  Thanks for volunteering!
