### ISSUE TITLE
Release v1.0.0-M33

### ISSUE THREAD

**Issue by FrancescoSerra** [http4s/http4s-twirl#7]
Hi @rossabaker,
I drafted up the release v1.0.0-M33. Would you mind clicking the button? :-) 

Thanks!

**Comment by rossabaker** [comment]
It didn't let me use yours for some reason, but I copied and pasted a new one and gave you credit.  Thanks for getting it ready!

**Comment by FrancescoSerra** [comment]
Thanks @rossabaker ! I'd really like to clear up these blockers, so that you don't have to do all these back and forth's in order to action something that should be a mere press of a button. What can I do to help out with this?

**Comment by rossabaker** [comment]
I just tweaked the permissions.  I _think_ you'll be able to do the next one on your own.

**Comment by FrancescoSerra** [comment]
Cool. Let's see how it pans out next time
